Implementa provedor Lauro de Freitas Bahia
OpenAC-Net/OpenAC.Net.NFSe pull request #111
Opened 2022-08-19 23:00 UTC by DSBRBrasil

Segue para analise

2022-08-19 23:33 UTC, rftd commented
tem conflito na arquivo de cidades.

2022-08-19 23:34 UTC, rftd requested changes
Tem conflito no arquivo de cidades.

2022-08-19 23:34 UTC, rftd commented on src/OpenAC.Net.NFSe.Test/SetupOpenNFSe.cs
> +        public static OpenNFSe Abrasf => sigiss ?? (sigiss = GetAbrasf());
Estas variáveis não deveriam ser abrasaf ?

2022-08-19 23:34 UTC, rftd commented on src/OpenAC.Net.NFSe/Providers/Metropolisweb/MetropolisWebAbrasfClient.cs
> +                    contetType = $"application/soap+xml; charset={CharSet};action={soapAction}";
por que copiou o duplicou o código da classe base ???

2022-08-19 23:34 UTC, rftd commented on src/OpenAC.Net.NFSe/Providers/Metropolisweb/MetropolisWebAbrasfClient.cs
> +                    envelope.Append("<soapenv:Envelope xmlns:end=\"http://endpoint.nfse.ws.webservicenfse.edza.com.br/\" xmlns:soapenv=\"http://schemas.xmlsoap.org/soap/envelope/\">");
se fosse só pelo namespace bastava passar para função !

2022-08-20 10:59 UTC, DSBRBrasil commented on src/OpenAC.Net.NFSe.Test/SetupOpenNFSe.cs
> +        public static OpenNFSe Abrasf => sigiss ?? (sigiss = GetAbrasf());
nao entendi ?

2022-08-20 10:59 UTC, DSBRBrasil commented on src/OpenAC.Net.NFSe/Providers/Metropolisweb/MetropolisWebAbrasfClient.cs
> +                    envelope.Append("<soapenv:Envelope xmlns:end=\"http://endpoint.nfse.ws.webservicenfse.edza.com.br/\" xmlns:soapenv=\"http://schemas.xmlsoap.org/soap/envelope/\">");
ok, resolvi no proximo pullrequest

2022-08-27 03:06 UTC, merged