Inclusão do provider de Brasília
OpenAC-Net/OpenAC.Net.NFSe pull request #153
Opened 2022-10-28 13:54 UTC by jairgmjunior1

inclusão de brasilia no arquivo de municípios.
inclusão de alguns atributos na entidades.
Criação do Tipo Dedução seguindo o padrão da Natureza de Operação.
Alteração no provider do provider DSF que utiliza o Tipo de Dedução.  linha  241 e 1122 no arquivo ProviderDSF.cs

2022-11-02 00:52 UTC, rftd requested changes

2022-11-02 00:52 UTC, rftd commented on src/OpenAC.Net.NFSe/Providers/Curitiba/ProviderCuritiba.cs
> -            var construcao = new XElement("ContrucaoCivil");
porque mudou aqui, estava com erro no provedor ?
As vezes os provedores colocam as tag com nome errado.

2022-11-02 00:52 UTC, rftd commented on src/OpenAC.Net.NFSe/Nota/ResponsavelRetencao.cs
> -        Tomador,
qual o motivo de remover os campos aqui ?

2022-11-03 10:01 UTC, jairgmjunior1 commented on src/OpenAC.Net.NFSe/Providers/Curitiba/ProviderCuritiba.cs
> -            var construcao = new XElement("ContrucaoCivil");
bom, eu estava fazendo uns testes antes de iniciar outro provedor, e no confronto resultou erro nessa tag, eu apenas ajustei nessa também, pensando estar errado.

2022-11-08 01:27 UTC, rftd requested changes

2022-11-08 01:27 UTC, rftd commented on src/OpenAC.Net.NFSe/Providers/Curitiba/ProviderCuritiba.cs
> -            var construcao = new XElement("ContrucaoCivil");
então segundo o schema esta correto o ContrucaoCivil, favor alterar de volta.

2022-11-08 01:27 UTC, rftd commented on src/OpenAC.Net.NFSe/Nota/ResponsavelRetencao.cs
> -        Tomador,
senão tiver motivo para remover deixe como esta e coloque os novos itens apenas.

2022-11-15 01:33 UTC, rftd requested changes

2022-11-15 01:33 UTC, rftd commented on src/OpenAC.Net.NFSe/Providers/ISSNet/ProviderISSNet.cs
> -            var construcao = new XElement("ContrucaoCivil");
Aqui tbm não deveria mudar senão tiver conferido com o schema.

2022-12-21 00:05 UTC, adrianotrentim commented on src/OpenAC.Net.NFSe/Providers/Curitiba/ProviderCuritiba.cs
> -            var construcao = new XElement("ContrucaoCivil");
É, Smar APD por exemplo (se não me engano) é errado tbm, como ContrucaoCivil

2024-09-26 12:42 UTC, closed without merging