Implementação inicial do provedor SIAPNet
OpenAC-Net/OpenAC.Net.NFSe pull request #64
Opened 2022-04-18 17:53 UTC by transis2

2022-04-19 02:42 UTC, rftd requested changes

2022-04-19 02:42 UTC, rftd commented on src/OpenAC.Net.NFSe/Providers/AssessorPublico/AssessorPublicoServiceClient.cs
> +            message.Append(msg.Replace("<", "&lt;").Replace(">", "&gt;"));
use AppendEnvio aqui que já faz estes replaces necessarios.

2022-04-19 02:42 UTC, rftd commented on src/OpenAC.Net.NFSe/Providers/AssessorPublico/AssessorPublicoServiceClient.cs
> +            message.Append(msg.Replace("<", "&lt;").Replace(">", "&gt;"));
use AppendEnvio aqui que já faz estes replaces necessarios.

2022-04-19 11:28 UTC, transis2 reviewed
Pronto

2022-04-19 11:28 UTC, transis2 commented on src/OpenAC.Net.NFSe/Providers/AssessorPublico/AssessorPublicoServiceClient.cs
> +            message.Append(msg.Replace("<", "&lt;").Replace(">", "&gt;"));
Feito

2022-04-19 11:28 UTC, transis2 commented on src/OpenAC.Net.NFSe/Providers/AssessorPublico/AssessorPublicoServiceClient.cs
> +            message.Append(msg.Replace("<", "&lt;").Replace(">", "&gt;"));
Feito

2022-04-22 03:18 UTC, rftd approved these changes

2022-04-22 03:18 UTC, merged